### ISSUE TITLE
.show is no longer supported for FigureCanvasTkAgg

### ISSUE THREAD

**Issue by jbrinchmann** [agabrown/astrometry-inference-tutorials#3]
This is also regarding DistanceEstimatorApplication.py - when showing the PDFs it calls plot_image which uses the show() option to FigureCanvasTkAgg - this is no longer (not sure which matplotlib version) supported and .draw should be used instead. I use:

```        
        if hasattr(dataPlot, 'show'):
            # Deprecated version
            dataPlot.show()
        elif hasattr(dataPlot, 'draw'):
            dataPlot.draw()
        else:
            # Maybe print a warning?
            return
```

**Comment by agabrown** [comment]
Thanks for spotting this and providing the solution!
